import {
  findDiscNumberInFolderStructure,
  findArtistNameInFolderStructure,
  findReleaseNameInFolderStructure,
  findReleaseYearInFolderStructure,
  findTrackNameInFolderStructure,
  findTrackNumberInFolderStructure,
} from './indexing.music-folder-structure'

describe('Music indexing', () => {
  describe('Find metadata in folder structure', () => {
    test('Disc number', () => {
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD-2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/Disc 2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/Disc2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/Disc-2/09 Psychopomp.mp3'))
        .toEqual(2)
      expect(findDiscNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(null)
    })
    test('Artist name', () => {
      expect(findArtistNameInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual('Thank You Scientist')
      expect(findArtistNameInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual('Thank You Scientist')
    })
    test('Release name', () => {
      expect(findReleaseNameInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual('Stranger Heads Prevail')
      expect(findReleaseNameInFolderStructure('/home/user1/music/Thank You Scientist/2016Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual('2016Stranger Heads Prevail')
      expect(findReleaseNameInFolderStructure('/home/user1/music/Thank You Scientist/2016 - Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual('Stranger Heads Prevail')
      expect(findReleaseNameInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual('Stranger Heads Prevail')
      expect(findReleaseNameInFolderStructure('/home/user1/music/Thank You Scientist/2016-Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual('Stranger Heads Prevail')
    })
    test('Release year', () => {
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/09 Psychopomp.mp3'))
        .toEqual(2016)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/(2016) Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(2016)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/2016 Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(2016)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/2016-Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(2016)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/2016 - Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(2016)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/2016Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(null)
      expect(findReleaseYearInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(null)
    })
    test('Track name', () => {
      expect(findTrackNameInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/Psychopomp.mp3'))
        .toEqual('Psychopomp')
      expect(findTrackNameInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual('Psychopomp')
      expect(findTrackNameInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 - Psychopomp.mp3'))
        .toEqual('Psychopomp')
    })
    test('Track number', () => {
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/[2016] Stranger Heads Prevail/CD 2/9 Psychopomp.mp3'))
        .toEqual(9)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 Psychopomp.mp3'))
        .toEqual(9)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09-Psychopomp.mp3'))
        .toEqual(9)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/09 - Psychopomp.mp3'))
        .toEqual(9)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/(0009) Psychopomp.mp3'))
        .toEqual(9)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Thank You Scientist/Stranger Heads Prevail/Psychopomp.mp3'))
        .toEqual(null)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Dream Theater/[2002] Six Degrees of Inner Turbulence/1-04 - The Great Debate.flac'))
        .toEqual(4)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Dream Theater/[2002] Six Degrees of Inner Turbulence/(2-7) - The Great Debate.flac'))
        .toEqual(7)
      expect(findTrackNumberInFolderStructure('/home/user1/music/Dream Theater/[2002] Six Degrees of Inner Turbulence/02-10 - The Great Debate.flac'))
        .toEqual(10)
    })
  })
})
