services:
  # Dev database for the media server
  cardinal-media-server-pg-dev:
    container_name: cardinal-db-media-server
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - cardinal-media-server-pg-db-data:/var/lib/postgresql/data
    networks:
      database-network:
        ipv4_address: 172.20.0.4

  # Database for the auth server
  cardinal-auth-dev:
    container_name: cardinal-db-auth-server
    image: mongo:7.0.12
    restart: always
    volumes:
      - cardinal-auth-server:/data/db
    ports:
      - "27017:27017"
    networks:
      database-network:
        ipv4_address: 172.20.0.3

  # Database for the CMS
  cardinal-cms-dev:
    container_name: cardinal-db-cms
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - cardinal-cms:/var/lib/postgresql/data
    networks:
      database-network:
        ipv4_address: 172.20.0.2

# Local static network for all databases
networks:
  database-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  cardinal-media-server-pg-db-data:
    name: "cardinal-media-server-pg-db-data"
  cardinal-auth-server:
    name: "cardinal-auth-server-db-data"
  cardinal-cms:
    name: "cardinal-cms-db-data"
