diff a/Dockerfile.media-server b/Dockerfile.media-server	(rejected hunks)
@@ -2,8 +2,8 @@
 # glibc because the binary is built on a glibc system.
 FROM node:18
 
-ARG UNIQUE_RELEASE_TAG
-ENV UNIQUE_RELEASE_TAG ${UNIQUE_RELEASE_TAG}
+ARG BUILD_TAG
+ENV BUILD_TAG ${BUILD_TAG}
 
 # TODO development env
 ENV NODE_ENV production
@@ -13,8 +13,8 @@ ENV CARDINAL_CONTAINER true
 # TODO use port 24800 in development env
 ENV CARDINAL_HOME_SERVER_PORT 24900
 
-# TODO beta channels
-ENV RELEASE_CHANNEL stable
+ARG RELEASE_CHANNEL
+ENV RELEASE_CHANNEL ${RELEASE_CHANNEL}
 
 WORKDIR /home/node
 
